service: identity-mapper

app: identity_mapper_dev
tenant: tolufakiyesi

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${self:provider.stage}}
  region: eu-west-1
functions:
  getRecord:
    handler: handler.getRecord
    events: 
      - http:
          path: /
          method: get   
      - http:
          path: /record
          method: get
          cors: true
  postRecord:
    handler: handler.postRecord
    events:
      - http:
          path: /record
          method: post
          cors: true
plugins:
- serverless-offline