service: my-service

app: myapp-dev
tenant: tolufakiyesi

provider:
  name: aws
  runtime: nodejs8.10
functions:
  receives_payload:
    handler: handler.receives_payload
    events:    
      - http:
          path: /user
          method: get
      - http:
          path: /user
          method: post
plugins:
- serverless-offline