service: identity-mapping-engine

app: identity_mapping_engine
tenant: tolufakiyesi || Morifeoluwa Jebutu

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${self:provider.stage}}
  region: eu-west-1
functions:
  receives_payload:
    handler: handler.Controller
    events:    
      - http:
          path: /user
          method: get
      - http:
          path: /user
          method: post
plugins:
- serverless-offline