service: identity-mapper

app: identity_mapper_dev
tenant: tolufakiyesi

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${self:provider.stage}}
  region: eu-west-1
functions:
  record:
    handler: handler.record
    events: 
      - http:
          path: /
          method: get   
      - http:
          path: /record
          method: get
      - http:
          path: /record
          method: post
plugins:
- serverless-offline