service: identity-mapper

app: identity_mapper_dev
tenant: tolufakiyesi

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${self:provider.stage}}
  region: eu-west-1
functions:
  receives_payload:
    handler: handler.receives_payload
    events:    
      - http:
          path: /user
          method: get
      - http:
          path: /user
          method: post
plugins:
- serverless-offline