AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS lambda function that for generating unique tap-ids

Globals:
    Function:
        Timeout: 200

Resources:
  Users:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        ListUsers:
          Type: Api
          Properties:
            Path: /user
            Method: get        
        GetUsers:
          Type: Api
          Properties:
            Path: /user
            Method: post
      Environment:
        Variables: 
          S3_BUCKET: bucket-name